### ISSUE TITLE
Android 11 - OOS OB 1 - Vendor Dump

### ISSUE THREAD

**Issue by LaNataliaaa** [Chandra-Chaganti/device_oneplus_oneplus7pro_dummy#1]
Could you pleasee do a vendor dump same as AndroidBlobs git please? I can't seem to achieve -adb root - for the extract script. Thanks.

**Comment by Chandra-Chaganti** [comment]
> Could you pleasee do a vendor dump same as AndroidBlobs git please? I can't seem to achieve -adb root - for the extract script. Thanks.

https://git.rip/dumps/oneplus/oneplus7pro
